### ISSUE TITLE
Not able to attach files or use the file chooser at all

### ISSUE THREAD

**Issue by esijg** [flathub/com.github.bleakgrey.tootle#1]
![mynd](https://user-images.githubusercontent.com/2924543/45873771-bd0dda80-bd82-11e8-9707-897f51d264e5.png)

I am on Ubuntu 18.04, when clicking the attach button (paperclip) the file chooser dialog shows only empty folders, unless I go into the root, then I start seeing other folders until I reach my user folder which appears empty.

My guess is that this is possibly a flatpak issue rather than a tootle issue

**Comment by bilelmoussaoui** [comment]
As far as I'm concerned, this can be fixed either by giving the application the full permission to the home directory or by the application using the NativeFileChooser. Will see what upstream thinks about it

**Comment by bilelmoussaoui** [comment]
@TingPing Do you think it's good to give it the home directory permission until it's fixed upstream?

**Comment by TingPing** [comment]
It is probably a 10 line patch to fix it today: https://github.com/bleakgrey/tootle/blob/master/src/Widgets/AttachmentBox.vala#L39-L46

**Comment by rodneyrod** [comment]
How's the progress with NativeFileChooser coming along?
