### ISSUE TITLE
Project is "Archived" on github. => Should be decommissioned

### ISSUE THREAD

**Issue by BrunoVernay** [flathub/com.github.bleakgrey.tootle#23]
I do not know if there is a policy for Flathub, but the project repository (https://github.com/bleakgrey/tootle) being clearly archived 
"This repository has been archived by the owner. It is now read-only."

It means that the project is dead. Will not receive any update. It has 60 open issues that will never be fixed, and one cannot add new ones.

There is no indication about the project status on Flathub.

**Comment by orowith2os** [comment]
Got a PR open for it here: https://github.com/flathub/com.github.bleakgrey.tootle/pull/24
