### ISSUE TITLE
Notification icon is missing 

### ISSUE THREAD

**Issue by ahayzen** [flathub/com.github.bleakgrey.tootle#4]
It appears that the notification icon is missing in the header bar
![image](https://user-images.githubusercontent.com/3669750/47120099-669e9980-d265-11e8-9abc-13da195eb3c3.png)
And also in the list of notifications
![image](https://user-images.githubusercontent.com/3669750/47120126-7e761d80-d265-11e8-9b03-21342a0969fa.png)

**Comment by bilelmoussaoui** [comment]
Will patch it tomorrow to use the elementary icons & gtk theme as the rest of elementary apps on Flathub.

**Comment by bilelmoussaoui** [comment]
Fixed. You should receive an update soon with the patched application to use the Gtk & Icons theme from elementary.
