### ISSUE TITLE
Broken UX on KDE

### ISSUE THREAD

**Issue by jalcine** [flathub/com.github.bleakgrey.tootle#8]
The patch made [here][1] ruins the experience of me using Tootle on KDE.
![screenshot_20181212_095009](https://user-images.githubusercontent.com/452100/49905719-b17efc80-fe23-11e8-81d4-1a489d239cde.png)

Video: https://noctule.jacky.wtf/s/9PHoAzL3JorWCEx

[1]: https://github.com/flathub/com.github.bleakgrey.tootle/blob/master/elementary-theme.patch

**Comment by bilelmoussaoui** [comment]
Not the app issue. It's a KWin issue, , report upstream, please.

**Comment by jalcine** [comment]
It is an app issue; Tootle or the Flatpak provided by Tootle is enforcing a client side theme that doesn't exist on my machine.

How did you determine it being a KWin issue without even testing it?

**Comment by jalcine** [comment]
The bug is occurring because of this extraneous patch: https://github.com/flathub/com.github.bleakgrey.tootle/blob/master/elementary-theme.patch

It doesn't provide any user value and when I remove it, the application works fine.

**Comment by cagatay-y** [comment]
GTK+ just fallbacks to an existing theme when the requested theme is not found. Also, looking at the screenshot you posted, it looks like you have the theme. I wonder how you determined it was not tested, or the issue is caused by theming.
Also, that patch does provide user value, just look at elementary/stylesheet#4.  The app is intended to be used with the elementary theme and designed according to that. If you want to read more on why one cannot simply change the theme and hope it works, there is a nice blog post on that: https://blogs.gnome.org/tbernard/2018/10/15/restyling-apps-at-scale/

**Comment by bilelmoussaoui** [comment]
As I mentioned before, the theme is embedded in the app itself. The app is having the theme, I'm pretty sure that KWin doesn't render either the client side decoration or has an issue with rendering the window's shadow.

**Comment by Mikaela** [comment]
Hi, I just asked about this at #kde on freenode wondering if I should open the issue to KWin and and they suggested me to:

* Alt + F3 -> More actions -> Special Window Settings -> Appreance & Fixes
    * [x] No titlebar and frame | Force | No
    * [x] Window type | Force | Normal Window

* `gnome-screenshot -i` *Grab the current window*

![and this is the result](https://user-images.githubusercontent.com/831184/51491933-d9109f80-1da7-11e9-8556-6a65d95080bb.png)

From here they said that it seems that Tootle is making a much bigger window than necessary and thus there is a little that KWin can make to do towards this, so I think this issue should be reopened.

**Comment by bilelmoussaoui** [comment]
How should I fix it here, please? Other than removing the elementary theme patch I don't see any possible ways to fix it, which will just make the application look unfinished with ugly widgets and missing icons.

Can you please open the Gtk inspector, select the main window and send a screenshot of the classes that are used? What If you switch the gtk theme to Adwaita on the Gtk Inspector, does it fix the issue?

**Comment by TingPing** [comment]
@bilelmoussaoui 	Its probably a bug in the elementary theme (or custom css the app has) so I'd discuss it with them.

**Comment by bilelmoussaoui** [comment]
@TingPing A lot of elementary apps with the pached theme have somehow the same issue on KDE (not only KDE?)
See this one for example: https://github.com/flathub/com.github.robertsanseries.ciano/issues/3

**Comment by Mikaela** [comment]
> Can you please open the Gtk inspector, select the main window and send a screenshot of the classes that are used?

I fear I don't understand what you are asking, does this look correct?

![screenshot from 2019-01-21 20-29-58](https://user-images.githubusercontent.com/831184/51492727-ba5fd800-1daa-11e9-84fe-21a3a7e882f5.png)

> What If you switch the gtk theme to Adwaita on the Gtk Inspector, does it fix the issue?

Yes, it does.

![screenshot from 2019-01-21 20-30-46](https://user-images.githubusercontent.com/831184/51492738-c0ee4f80-1daa-11e9-83f0-41d690fdb48a.png)

This is the first time I have ever opened GTK inspector, I had to Google what it is and how do I get it open. I found and followed the instructions from https://askubuntu.com/a/748152.

**Comment by TingPing** [comment]
> A lot of elementary apps with the pached theme have somehow the same issue on KDE (not only KDE?)

On GNOME the initial window has a massive border around it to.

**Comment by bilelmoussaoui** [comment]
Ok, it seems to be an elementary theme issue. They don't have a `.solid-csd` defined on their stylesheet. Will open an issue upstream about that. 
https://github.com/elementary/granite/issues/812
Elementary guys have the same issue on their platform too with apps like PlayOnLinux.  Will backport the patch to the elementary baseApp once it's fixed upstream.

**Comment by bilelmoussaoui** [comment]
Can someone try to reproduce this after today's update?

**Comment by jalcine** [comment]
I'll try it.

**Comment by jalcine** [comment]
![Screenshot_20191011_133609](https://user-images.githubusercontent.com/452100/66683406-35fd0000-ec2c-11e9-98f0-c672f7e02cba.png)

Still getting a border.

**Comment by bilelmoussaoui** [comment]
Sorry, the latest build wasn't published yet. It should be there in few minutes

**Comment by jalcine** [comment]
Last update on https://flathub.org/apps/details/com.github.bleakgrey.tootle looks like it was a year ago?

**Comment by bilelmoussaoui** [comment]
Because the release date from that page shows the "real" release date. I just bumped the runtime, GTK & icon themes.

**Comment by nyx-lyb3ra** [comment]
:eyes: since Tootle is not using the elementary theme anymore, I think this can be closed, right?

**Comment by jalcine** [comment]
Yeah.

Also, lol, I use elementary now so 🤷🏾
