### ISSUE TITLE
Cannot sign in; "SSL handshake failed"

### ISSUE THREAD

**Issue by wjt** [flathub/com.github.bleakgrey.tootle#9]
Trying to sign in, I enter my instance name (I tried `mastodon.social` and `botsin.space`) and see:

> **Network Error*
> SSL handshake failed

![screenshot from 2019-01-09 17-57-44](https://user-images.githubusercontent.com/86760/50918471-37e52900-1438-11e9-9a65-57e36f8e54fb.png)

I see this on both Endless OS (internal development branch) and Fedora 29.

**Comment by bilelmoussaoui** [comment]
Does it happen if you build the package yourself? I'm not having the issue here. I'm pretty sure it's an issue somewhere upstream as they forgot to disable ssl_strict on their libsoup communications or something like that.

**Comment by wjt** [comment]
Yes, if I build it myself I see the same issue:

```
$ flatpak install --user flathub io.elementary.BaseApp/x86_64/juno
$ flatpak-builder --install --user app com.github.bleakgrey.tootle.json
$ flatpak run com.github.bleakgrey.tootle/x86_64/master
```

(I would be sad if that were not the case, because it would mean the build isn't reproducible!)

> I'm pretty sure it's an issue somewhere upstream as they forgot to disable ssl_strict on their libsoup communications or something like that.

`SoupSocket:ssl-strict` is documented as:

> Whether certificate errors should be considered a connection error.

Surely this should enabled? An invalid certificate should prevent the connection being established.

**Comment by bilelmoussaoui** [comment]
What I meant by building it yourself, is by building it from source code. Do you have any flatpaked app that requires network access that you could try please?

**Comment by wjt** [comment]
Yes, many. I'm typing this in a Flatpak:d Firefox, for example, and GNOME Boxes from Flathub is happily downloading a new Ubuntu ISO, Slack is running, Transmission is downloading a new Endless OS ISO.

**Comment by bilelmoussaoui** [comment]
Will check that as soon as possible

**Comment by cagatay-y** [comment]
It looks like an upstream issue:
https://github.com/bleakgrey/tootle/issues/121

**Comment by wjt** [comment]
Must've been something to do with the runtime – this works now.

**Comment by bilelmoussaoui** [comment]
@wjt Magic of flatpak! Thanks for reporting back.
